# Generated by Django 3.0.6 on 2021-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AddField(
            model_name='employees',
            name='dob',
            field=models.CharField(default='13aug', max_length=20),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='mobile',
            field=models.IntegerField(default=123456),
        ),
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firtname',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(default='SOME STRING', max_length=10),
        ),
    ]
