# Generated by Django 3.0.6 on 2021-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210212_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firtname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
