# Generated by Django 3.0.6 on 2021-02-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210213_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
