# Generated by Django 3.0.6 on 2021-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210213_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.IntegerField(default=9999999999),
        ),
    ]
