# Generated by Django 3.0.6 on 2021-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210213_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='dob',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
