# Generated by Django 3.0.6 on 2021-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210213_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='dob',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='password',
            field=models.TextField(max_length=20),
        ),
    ]
